chore(ci): improve URL handling

diff --git a/.github/workflows/.deploy.yml b/.github/workflows/.deploy.yml
--- a/.github/workflows/.deploy.yml
+++ b/.github/workflows/.deploy.yml
@@ -84,14 +84,21 @@ jobs:
             echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
           fi
 
-          if [ -z "${{ inputs.url }}" ]; then
-            echo "Creating URL"
-            echo "url=fom-$(( ${{ inputs.target }} % 50 )).apps.silver.devops.gov.bc.ca"
-            echo "url=fom-$(( ${{ inputs.target }} % 50 )).apps.silver.devops.gov.bc.ca" >> $GITHUB_OUTPUT
-          else
+          if [ ! -z "${{ inputs.url }}" ]; then
             echo "Using URL parameter"
             echo "url=${{ inputs.url }}"
             echo "url=${{ inputs.url }}" >> $GITHUB_OUTPUT
+          elif [ -z "${{ inputs.url }}" ] && [ '${{ github.event_name }}' == 'pull_request' ]; then
+            echo "Creating URL from github.event.number mod 50"
+            echo "url=fom-$(( ${{ inputs.target }} % 50 )).apps.silver.devops.gov.bc.ca"
+            echo "url=fom-$(( ${{ inputs.target }} % 50 )).apps.silver.devops.gov.bc.ca" >> $GITHUB_OUTPUT
+          elif [ -z "${{ inputs.url }}" ] && [ '${{ github.event_name }}' != 'pull_request' ]; then
+            echo "Creating URL from inputs.target"
+            echo "url=fom-${{ inputs.target }}.apps.silver.devops.gov.bc.ca"
+            echo "url=fom-${{ inputs.target }}.apps.silver.devops.gov.bc.ca" >> $GITHUB_OUTPUT
+          else
+            echo "Unable to create URL"
+            exit 1
           fi
 
       - name: OpenShift Init
