Update db upgrade script to move postgis step after data restore.

diff --git a/.github/workflows/db-major-upgrade.yml b/.github/workflows/db-major-upgrade.yml
--- a/.github/workflows/db-major-upgrade.yml
+++ b/.github/workflows/db-major-upgrade.yml
@@ -205,18 +205,6 @@ jobs:
           exit 1
         fi
 
-    - name: Verify PostGIS Extension Installation at DB Upgrade Container
-      run: |
-        echo "Verifying PostGIS extension is installed..."
-        POSTGIS_VERSION=$(oc exec deployment/${NAME}-${ZONE}-${COMPONENT}-${DB_UPGRADE_VERSION} -n ${{ vars.OC_NAMESPACE }} -- \
-          bash -c 'psql -U $POSTGRES_USER -d $POSTGRES_DB -tAc "SELECT extversion FROM pg_extension WHERE extname = '\''postgis'\'';"')
-        if [ -z "$POSTGIS_VERSION" ]; then
-          echo "Error: PostGIS extension is not installed."
-          exit 1
-        else
-          echo "PostGIS extension is installed. Version: $POSTGIS_VERSION"
-        fi
-
     - name: Restore From Backup Into New Database
         # Restore previous 'pg_dump' backup dump file into new version db.
       env:
@@ -242,6 +230,18 @@ jobs:
         else
           echo "Error: Database restoration verification failed. No tables found."
           exit 1
+        fi
+
+    - name: Verify PostGIS Extension Installation at DB Upgrade Container
+      run: |
+        echo "Verifying PostGIS extension is installed..."
+        POSTGIS_VERSION=$(oc exec deployment/${NAME}-${ZONE}-${COMPONENT}-${DB_UPGRADE_VERSION} -n ${{ vars.OC_NAMESPACE }} -- \
+          bash -c 'psql -U $POSTGRES_USER -d $POSTGRES_DB -tAc "SELECT extversion FROM pg_extension WHERE extname = '\''postgis'\'';"')
+        if [ -z "$POSTGIS_VERSION" ]; then
+          echo "Error: PostGIS extension is not installed."
+          exit 1
+        else
+          echo "PostGIS extension is installed. Version: $POSTGIS_VERSION"
         fi
 
     - name: Scale Down Old Database Component
